### PR TITLE
working on quickstart vignette

### PR DESCRIPTION
**Pull request by bbolker**
- my comments/questions as (BB: ...)
- Picky, but I'd like to move toward more active voice generally ("we will", "you can" ...)
- I use `htmltools`, `visNetwork` here ... don't know whether they should be put in "Suggests" for the package or not?
- I noticed a small glitch in the `?Compartmental` documentation (state labels for the `sir` object are in `sir$labels$state()`, not `sir$state_labels` ...)

### CODE REVIEW

**Review by stevencarlislewalker — APPROVED** [review]
Thank you!

Your diagram code is very much appreciated.  I like the idea of a `macpan.helpers` package, and will create one although I will likely not be contributing much to it at least for the time being.

Similarly pleased with your illustration of using standard R tools to manipulate simulation results.

I actually like your idea of clarifying the different options for handling `N` in the `foi`

I agree that long format is more common.  I'll look for a non-wikipedia reference.  Maybe some Hadley JSS paper.

Thanks for identifying unclear points.

**Comment by papsti** [comment]
predictably, i like all of @bbolker's edits as well. will try to use active voice more!

@stevencarlislewalker, seconding the idea for a `macpan2.helpers` package.

**Comment by papsti** [comment]
wonderful, let me know when it's set up as an R package and i'll add a function to make a `visNetwork` graph of a `Compartmenal` object, which i just wrote using ben's vn code. i can then add `macpan2helpers` to the `Suggests` field of `macpan2` for use within vignettes.

**Comment by papsti** [comment]
should i fork to contribute or will you add me as a contributor?

**Comment by stevencarlislewalker** [comment]
Oops ... you are a contributor now, of course!  That was an oversight.

**Pull request merged**
