### PR TITLE
SHIVER and NFDS models and package docs

### PR DESCRIPTION
**Pull request by stevencarlislewalker**

### CODE REVIEW

**Comment by stevencarlislewalker** [comment]
Still failing eh? I'll have a look @jfree-man.

**Comment by jfree-man** [comment]
I think it's because `get_mod_info` is looking for 'title' and 'index_entry' in the .md file. When I have both an .Rmd and .md, the yaml header isn't pasted in the .md. I'm trying to think of options now.

**Comment by stevencarlislewalker** [comment]
Can't you just completely ignore the `.Rmd` file?

**Comment by stevencarlislewalker** [comment]
OK so why don't you just get the header information from the first file that has it, working in the following order?  `md`, `Rmd`, `Qmd`?

**Comment by jfree-man** [comment]
Good idea, I didn't think of this. I'll try that.

**Pull request merged**
